//Last updated 20240403 (Igor: removed url params)

AlexAI.mapOfKeyWords.set("blog", ["https://sailing-blog.nauticed.org/", "Sailing Blog", "Go to the "]);
AlexAI.mapOfKeyWords.set("anchoring", ["https://www.nauticed.org/sailing-courses/view/anchoring-a-sailboat", "Anchoring a Sailboat Course", "View the "]);
AlexAI.mapOfKeyWords.set("assessment", ["https://www.nauticed.org/sailing-schools", "NauticEd school or instructor", "Get assessed for certification with a "]);
AlexAI.mapOfKeyWords.set("bareboat bundle", ["https://www.nauticed.org/bundle/view/bareboatcharter", "Bareboat Bundle of Courses", "Go to the "]);
AlexAI.mapOfKeyWords.set("bareboat charter clinic", ["https://www.nauticed.org/sailing-courses/view/bareboat-charter", "Bareboat Charter Clinic", "View the "]);
AlexAI.mapOfKeyWords.set("bareboat charter master", ["https://www.nauticed.org/bundle/view/bareboatcharter", "Bareboat Charter Master", "Become a "]);
AlexAI.mapOfKeyWords.set("basic sail trim", ["https://www.nauticed.org/sailing-courses/view/basic-sail-trim", "Basic Sail Trim Course", "Free "]);
AlexAI.mapOfKeyWords.set("british virgin islands chart briefing", ["https://www.nauticed.org/sailing-courses/view/british-virgin-islands-chart-briefing", "British Virgin Islands Chart Briefing", "View the "]);
AlexAI.mapOfKeyWords.set("bvi chart briefing", ["https://www.nauticed.org/sailing-courses/view/british-virgin-islands-chart-briefing", "BVI Chart Briefing", "Here is the"]);
AlexAI.mapOfKeyWords.set("captain bundle", ["https://www.nauticed.org/bundle/view/captain", "Captain Bundle of Courses", "Learn offshore sailing with the "]);
AlexAI.mapOfKeyWords.set("catamaran sailing", ["https://www.nauticed.org/sailing-courses/view/catamaran-sailing-confidence", "Catamaran Sailing Confidence Course", "View the "]);
AlexAI.mapOfKeyWords.set("celestial navigation", ["https://www.nauticed.org/sailing-courses/view/introductory-celestial-navigation", "Celestial Navigation Course", "View the "]);
AlexAI.mapOfKeyWords.set("coastal navigation", ["https://www.nauticed.org/sailing-courses/view/coastal-navigation", "Coastal Navigation Online", "View the "]);
AlexAI.mapOfKeyWords.set("course", ["https://www.nauticed.org/sailing-courses", "NauticEd Sailing Courses", "View all of the "]);
AlexAI.mapOfKeyWords.set("dinghy sailing", ["https://www.nauticed.org/sailing-courses/view/getting-started-in-dinghy-sailing", "Dinghy Sailing Course", "Get started with "]);
AlexAI.mapOfKeyWords.set("docking", ["https://www.nauticed.org/sailing-courses/view/maneuvering-under-power", "Docking Skills", "Master "]);
AlexAI.mapOfKeyWords.set("electronic navigation", ["https://www.nauticed.org/sailing-courses/view/electronic-navigation", "Electronic Navigation Course", "View the "]);
AlexAI.mapOfKeyWords.set("introduction to sailing", ["https://www.nauticed.org/sailing-courses/view/introduction-to-sailing", "Introduction to Sailing", "Get started with "]);
AlexAI.mapOfKeyWords.set("maneuvering", ["https://www.nauticed.org/sailing-courses/view/maneuvering-under-power", "Maneuvering Under Power Course", "We highly recommend the "]);
AlexAI.mapOfKeyWords.set("navigation rules", ["https://www.nauticed.org/sailing-courses/view/navigation-rules", "Navigation Rules Course", "Free "]);
AlexAI.mapOfKeyWords.set("qualified crew", ["https://www.nauticed.org/sailing-courses/view/qualified-crew-member", "Qualified Crew Online Course", "View the "]);
AlexAI.mapOfKeyWords.set("rya day skipper", ["https://www.nauticed.org/sailing-courses/view/rya-day-skipper", "RYA Day Skipper Knowledge Course", "View the "]);
AlexAI.mapOfKeyWords.set("safety at sea", ["https://www.nauticed.org/sailing-courses/view/safety-at-sea", "Safety at Sea Course", "View the "]);
AlexAI.mapOfKeyWords.set("sail trim course", ["https://www.nauticed.org/sailing-courses/view/sail-trim", "Sail Trim Course", "View the "]);
AlexAI.mapOfKeyWords.set("skipper", ["https://www.nauticed.org/bundle/view/skipper", "Skipper Large Keelboat Bundle of Courses", "Go to the "]);
AlexAI.mapOfKeyWords.set("skipper course", ["https://www.nauticed.org/sailing-courses/view/skipper", "Skipper Large Keelboat Course", "View the "]);
AlexAI.mapOfKeyWords.set("small keelboat", ["https://www.nauticed.org/sailing-courses/view/skipper-small-keelboat", "Small Keelboats", "Learn to sail "]);
AlexAI.mapOfKeyWords.set("storm tactics", ["https://www.nauticed.org/sailing-courses/view/storm-tactics", "Storm Tactics Course", "Prepare with the "]);
AlexAI.mapOfKeyWords.set("transformational instructor", ["https://www.nauticed.org/sailing-courses/view/the-transformational-instructor", "Transformational Instructor", "Become a "]);
AlexAI.mapOfKeyWords.set("virtual reality", ["https://www.nauticed.org/sailing-courses/view/virtual-reality-sailing", "Virtual Reality", "Learn sailing in "]);
AlexAI.mapOfKeyWords.set("vr", ["https://www.nauticed.org/sailing-courses/view/virtual-reality-sailing", "Virtual Reality Training", "Learn about "]);
AlexAI.mapOfKeyWords.set("weather", ["https://www.nauticed.org/sailing-courses/view/weather", "Weather Online Course", "View the "]);
AlexAI.mapOfKeyWords.set("yacht charter crew", ["https://www.nauticed.org/sailing-courses/view/yacht-charter-crew", "Yacht Charter Crew Course", "View the "]);
AlexAI.mapOfKeyWords.set("certificate", ["https://www.nauticed.org/sailing-certification", "NauticEd Sailing Certificate", "Get a  "]);
AlexAI.mapOfKeyWords.set("certification", ["https://www.nauticed.org/sailing-certification", "NauticEd Sailing Certification", "Get your "]);
AlexAI.mapOfKeyWords.set("coast guard", ["https://sailing-blog.nauticed.org/sailing-instruction-and-assessment-standards-uscg/", "Offical Sailing Education Body", "US Coast Guard recognizes NauticEd as an "]);
AlexAI.mapOfKeyWords.set("license", ["https://www.nauticed.org/SLC", "Sailing License", "Get your "]);
AlexAI.mapOfKeyWords.set("nasbla", ["https://sailing-blog.nauticed.org/sailing-instruction-and-assessment-standards-uscg/", "Offical Sailing Education Body", "NASBLA recognizes NauticEd as an "]);
AlexAI.mapOfKeyWords.set("slc", ["https://www.nauticed.org/SLC", "SLC International License", "Learn about the "]);
AlexAI.mapOfKeyWords.set("slc exam", ["https://www.nauticed.org/sailing-courses/view/slc-examination", "SLC Exam", "Take the FREE "]);
AlexAI.mapOfKeyWords.set("uscg", ["https://sailing-blog.nauticed.org/sailing-instruction-and-assessment-standards-uscg/", "Offical Sailing Education Body", "US Coast Guard recognizes NauticEd as an "]);
AlexAI.mapOfKeyWords.set("abacos", ["https://sailing-blog.nauticed.org/sailing-vacations/bahamas-abacos-yacht-charter/", "Abacos Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("aegean", ["https://www.nauticed.org/sailing-vacations", "Aegean Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("antigua", ["https://sailing-blog.nauticed.org/sailing-vacations/antigua-yacht-charter/", "Antigua Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("asia", ["https://www.nauticed.org/sailing-vacations", "Asia Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("australia", ["https://www.nauticed.org/sailing-vacations", "Australia Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("bahamas", ["https://sailing-blog.nauticed.org/sailing-vacations/bahamas-yacht-charter/", "Bahamas Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("barbuda", ["https://www.nauticed.org/sailing-vacations", "Barbuda Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("belize", ["https://sailing-blog.nauticed.org/sailing-vacations/belize-yacht-charter-and-sailing-vacations/", "Belize Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("british virgin islands", ["https://sailing-blog.nauticed.org/sailing-vacations/bvi-yacht-charter/", "BVI Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("bvi", ["https://sailing-blog.nauticed.org/sailing-vacations/bvi-yacht-charter/", "BVI Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("caledonia", ["https://www.nauticed.org/sailing-vacations", "Caledonia Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("canary", ["https://www.nauticed.org/sailing-vacations", "Canary Islands Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("caribbean", ["https://sailing-blog.nauticed.org/sailing-vacations/caribbean-yacht-charter/", "Caribbean Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("corsica", ["https://www.nauticed.org/sailing-vacations", "Corsica Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("croatia", ["https://sailing-blog.nauticed.org/sailing-vacations/croatia-yacht-charter/", "Croatia Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("europe", ["https://www.nauticed.org/sailing-vacations", "Europe Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("exumas", ["https://sailing-blog.nauticed.org/sailing-vacations/bahamas-yacht-charter/", "Exumas Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("france", ["https://www.nauticed.org/sailing-vacations", "France Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("greece", ["https://sailing-blog.nauticed.org/sailing-vacations/greece-yacht-charter-sailing-vacations/", "Greece Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("grenada", ["https://sailing-blog.nauticed.org/sailing-vacations/grenada-yacht-charter/", "Grenada Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("grenadines", ["https://sailing-blog.nauticed.org/sailing-vacations/saint-vincent-grenadines-yacht-charter-and-sailing-vacations/", "Grenadines Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("guadeloupe", ["https://sailing-blog.nauticed.org/sailing-vacations/guadeloupe-yacht-charter/", "Guadeloupe Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("italy", ["https://www.nauticed.org/sailing-vacations", "Italy Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("lucia", ["https://sailing-blog.nauticed.org/sailing-vacations/saint-lucia-yacht-charter/", "St. Lucia Yacht Charter Guide", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("malaysia", ["https://www.nauticed.org/sailing-vacations", "Malaysia Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("martin", ["https://sailing-blog.nauticed.org/sailing-vacations/saint-martin-yacht-charter-sailing-vacations/", "St. Martin Yacht Charter Guide", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("martinique", ["https://sailing-blog.nauticed.org/sailing-vacations/martinique-yacht-charter/", "Martinique Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("mediterranean", ["https://sailing-blog.nauticed.org/sailing-vacations/mediterranean-yacht-charter/", "Mediterranean Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("mexico", ["https://www.nauticed.org/sailing-vacations", "Mexico Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("new zealand", ["https://www.nauticed.org/sailing-vacations", "New Zealand Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("norway", ["https://www.nauticed.org/sailing-vacations", "Norway Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("pacific", ["https://www.nauticed.org/sailing-vacations", "Pacific Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("portugal", ["https://www.nauticed.org/sailing-vacations", "Portugal Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("puerto rico", ["https://sailing-blog.nauticed.org/sailing-vacations/puerto-rico-yacht-charter/", "Puerto Rico Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("san blas", ["https://www.nauticed.org/sailing-vacations", "San Blas Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("sea of cortez", ["https://www.nauticed.org/sailing-vacations", "Sea of Cortez Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("spain", ["https://www.nauticed.org/sailing-vacations", "Spain Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("spanish virgin islands", ["https://www.nauticed.org/sailing-vacations", "SVI Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("svi", ["https://www.nauticed.org/sailing-vacations", "SVI Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("sweden", ["https://www.nauticed.org/sailing-vacations", "Sweden Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("tahiti", ["https://www.nauticed.org/sailing-vacations", "Tahiti Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("thailand", ["https://www.nauticed.org/sailing-vacations", "Thailand Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("tonga", ["https://www.nauticed.org/sailing-vacations", "Tonga Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("turkey", ["https://sailing-blog.nauticed.org/sailing-vacations/turkey-yacht-charter-and-sailing-vacations/", "Turkey Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("us virgin islands", ["https://sailing-blog.nauticed.org/sailing-vacations/usvi-yacht-charter/", "UVI Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("uvi", ["https://sailing-blog.nauticed.org/sailing-vacations/usvi-yacht-charter/", "UVI Yacht Charter Guide", "View the "]);
AlexAI.mapOfKeyWords.set("vincent", ["https://sailing-blog.nauticed.org/sailing-vacations/saint-vincent-grenadines-yacht-charter-and-sailing-vacations/", "St. Vincent Yacht Charter Guide", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("amazon", ["https://sailing-blog.nauticed.org/sailing-books", "sailing books", "See NauticEd  "]);
AlexAI.mapOfKeyWords.set("asa", ["https://sailing-blog.nauticed.org/how-does-nauticed-compare-to-asa-and-us-sailing/", "How Nauticed compares", "See how "]);
AlexAI.mapOfKeyWords.set("book", ["https://sailing-blog.nauticed.org/sailing-books", "sailing books", "See NauticEd  "]);
AlexAI.mapOfKeyWords.set("toolkit", ["https://sailing-blog.nauticed.org/sailor-toolkit/", "Free Sailing Toolkit", "Your "]);
AlexAI.mapOfKeyWords.set("crew mate", ["https://support.nauticed.org/support/solutions/articles/44001787711-my-crewmates-have-not-received-request-emails", "CrewMates Here", "Learn more about "]);
AlexAI.mapOfKeyWords.set("crewmate", ["https://support.nauticed.org/support/solutions/articles/44001787711-my-crewmates-have-not-received-request-emails", "CrewMates Here", "Learn more about "]);
AlexAI.mapOfKeyWords.set("level", ["https://www.nauticed.org/faq-sailing-certificate#sailinglevels", "Levels and Ranks", "Learn about the "]);
AlexAI.mapOfKeyWords.set("rank", ["https://www.nauticed.org/faq-sailing-certificate#sailingranks", "Ranks and Levels", "Learn about the "]);
AlexAI.mapOfKeyWords.set("instructor", ["https://www.nauticed.org/sailing-schools", "Sailing Instructor", "Find a "]);
AlexAI.mapOfKeyWords.set("practical", ["https://www.nauticed.org/practical-sailing-courses", "Practical Courses", "Get on the water with "]);
AlexAI.mapOfKeyWords.set("school", ["https://www.nauticed.org/sailing-schools", "Sailing School", "Find a "]);
AlexAI.mapOfKeyWords.set("agent", ["https://www.nauticed.org/contactus", "Sailing Vacations Agent", "Contact a NauticEd "]);
AlexAI.mapOfKeyWords.set("contact", ["https://www.nauticed.org/contactus", "Contact NauticEd", ""]);
AlexAI.mapOfKeyWords.set("log in", ["https://support.nauticed.org/support/solutions/articles/44000496279-sign-in-issues", "Log In Instructions", "Go to "]);
AlexAI.mapOfKeyWords.set("login", ["https://support.nauticed.org/support/solutions/articles/44000496279-sign-in-issues", "Log In Instructions", "Go to "]);
AlexAI.mapOfKeyWords.set("password", ["https://support.nauticed.org/support/solutions/articles/44000496279-sign-in-issues", "Password Instructions", "Go to "]);
AlexAI.mapOfKeyWords.set("sign in", ["https://support.nauticed.org/support/solutions/articles/44000496279-sign-in-issues", "Sign In Instructions", "Go to "]);
AlexAI.mapOfKeyWords.set("signin", ["https://support.nauticed.org/support/solutions/articles/44000496279-sign-in-issues", "Sign In Instructions", "Go to "]);
AlexAI.mapOfKeyWords.set("student guide", ["https://www.nauticed.org/press/nauticed-student-guide.pdf", "Student Guide", "Read the "]);
AlexAI.mapOfKeyWords.set("support", ["https://www.nauticed.org/contactus", "NauticEd Support", "Get help at "]);
AlexAI.mapOfKeyWords.set("charter", ["https://www.nauticed.org/sailing-vacations", "Yacht Charter", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("sailing holiday", ["https://www.nauticed.org/sailing-vacations", "Sailing Vacation", "Inquire about a "]);
AlexAI.mapOfKeyWords.set("vacation", ["https://www.nauticed.org/sailing-vacations", "Sailing Vacation", "Inquire about a "]);